import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import OpenAI from "openai";
import { google } from "googleapis";
import fs from "node:fs";
import path from "node:path";

dotenv.config();

const app = express();
const port = process.env.PORT || 3000;
const allowedOrigin = process.env.ALLOWED_ORIGIN || "https://rainbow-alfajores-f0f29a.netlify.app";
const publicBaseUrl = process.env.PUBLIC_BASE_URL || "https://vexa-ai-companion-production.up.railway.app";
const redirectUri = process.env.GOOGLE_REDIRECT_URI || `${publicBaseUrl}/auth/google/callback`;
const telegramWebhookUrl = `${publicBaseUrl}/api/telegram/webhook`;
const timezone = "Asia/Makassar";
const stateDir = process.env.VEXA_STATE_DIR || "/data";
const fallbackStateDir = path.join(process.cwd(), ".vexa-data");
let activeStateDir = stateDir;
let stateFile = path.join(activeStateDir, "vexa-state.json");
let saveTimer = null;
let lastChatTopic = null;
let lastChatTopicAt = 0;
const chatTopicTtlMs = 30 * 60 * 1000;
let googleTokens = process.env.GOOGLE_REFRESH_TOKEN ? { refresh_token: process.env.GOOGLE_REFRESH_TOKEN } : null;
let telegramChatId = process.env.TELEGRAM_CHAT_ID || null;
let telegramChatLabel = process.env.TELEGRAM_CHAT_LABEL || null;
const telegramChats = new Map();
const telegramMessages = new Map();
function ensureStateDir(){try{fs.mkdirSync(activeStateDir,{recursive:true});fs.accessSync(activeStateDir,fs.constants.W_OK);}catch{activeStateDir=fallbackStateDir;stateFile=path.join(activeStateDir,"vexa-state.json");fs.mkdirSync(activeStateDir,{recursive:true});}}
function loadState(){ensureStateDir();try{if(!fs.existsSync(stateFile))return;const p=JSON.parse(fs.readFileSync(stateFile,"utf8"));if(p.googleTokens&&typeof p.googleTokens==="object")googleTokens={...googleTokens,...p.googleTokens};if(p.telegramChatId)telegramChatId=String(p.telegramChatId);if(p.telegramChatLabel)telegramChatLabel=String(p.telegramChatLabel);for(const c of Array.isArray(p.telegramChats)?p.telegramChats:[])if(c?.id)telegramChats.set(String(c.id),c);for(const r of Array.isArray(p.telegramMessages)?p.telegramMessages:[])if(r?.chatId&&Array.isArray(r.items))telegramMessages.set(String(r.chatId),r.items.slice(-500));console.log(`VEXA state dimuat dari ${stateFile}`);}catch(e){console.error("VEXA gagal memuat state:",e.message);}}
function saveStateNow(){try{ensureStateDir();const p={version:1,updatedAt:new Date().toISOString(),googleTokens,telegramChatId,telegramChatLabel,telegramChats:[...telegramChats.values()],telegramMessages:[...telegramMessages.entries()].map(([chatId,items])=>({chatId,items:items.slice(-500)}))};const tmp=`${stateFile}.tmp`;fs.writeFileSync(tmp,JSON.stringify(p,null,2),{mode:0o600});fs.renameSync(tmp,stateFile);}catch(e){console.error("VEXA gagal menyimpan state:",e.message);}}
function scheduleSaveState(){clearTimeout(saveTimer);saveTimer=setTimeout(saveStateNow,250);}function setChatTopic(t){lastChatTopic=t;lastChatTopicAt=Date.now();}function getChatTopic(){if(!lastChatTopic||Date.now()-lastChatTopicAt>chatTopicTtlMs)return null;return lastChatTopic;}loadState();
app.use(cors({origin(origin,cb){if(!origin||origin===allowedOrigin||origin.startsWith("http://localhost:"))return cb(null,true);return cb(new Error("Origin tidak diizinkan oleh VEXA."));}}));app.use(express.json({limit:"1mb"}));
function makeOAuthClient(){const id=process.env.GOOGLE_CLIENT_ID,secret=process.env.GOOGLE_CLIENT_SECRET;if(!id||!secret)throw new Error("Google OAuth credentials belum lengkap.");const c=new google.auth.OAuth2(id,secret,redirectUri);c.on("tokens",t=>{googleTokens={...googleTokens,...t};scheduleSaveState();});return c;}function getAuthorizedGoogleClient(){if(!googleTokens)return null;const c=makeOAuthClient();c.setCredentials(googleTokens);return c;}function cleanJson(t){return String(t||"").replace(/^```json\s*/i,"").replace(/```$/i,"").trim();}
async function telegramApi(method,payload={}){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error("TELEGRAM_BOT_TOKEN belum diatur.");const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.description||`Telegram API ${method} gagal.`);return d.result;}
function rememberTelegramMessage(m){const c=m?.chat;if(!c?.id)return;const id=String(c.id),label=c.title||[c.first_name,c.last_name].filter(Boolean).join(" ")||c.username||id;telegramChats.set(id,{id,label,type:c.type||"unknown"});if(!telegramChatId&&c.type==="private"){telegramChatId=id;telegramChatLabel=label;}const sender=m.from?.username?`@${m.from.username}`:[m.from?.first_name,m.from?.last_name].filter(Boolean).join(" ")||"Unknown",text=m.text||m.caption||"";if(text){const list=telegramMessages.get(id)||[];list.push({messageId:m.message_id,date:m.date,sender,text:String(text).slice(0,6000)});if(list.length>500)list.splice(0,list.length-500);telegramMessages.set(id,list);}scheduleSaveState();}
function findTelegramChatByName(name){const q=String(name||"").toLowerCase().trim();if(!q)return null;const cs=[...telegramChats.values()];return cs.find(c=>c.label.toLowerCase()===q)||cs.find(c=>c.label.toLowerCase().includes(q))||cs.find(c=>q.includes(c.label.toLowerCase()))||null;}function getTelegramGroupRows(){return [...telegramChats.values()].filter(c=>c.type==="group"||c.type==="supergroup").map(c=>({id:c.id,label:c.label,type:c.type,messageCount:(telegramMessages.get(c.id)||[]).length})).sort((a,b)=>a.label.localeCompare(b.label));}
function formatTelegramGroupsReply(){const g=getTelegramGroupRows();if(!g.length)return "Bang John, belum ada grup Telegram yang terbaca oleh VEXA. Kirim satu pesan baru di grup yang sudah memasukkan bot VEXA.";return `Bang John, grup Telegram yang sudah terbaca:\n${g.map((x,i)=>`${i+1}. ${x.label} — ${x.messageCount} pesan terbaca`).join("\n")}`;}
function getRecentTelegramReply(qn){const q=String(qn||"").toLowerCase(),g=getTelegramGroupRows();if(!g.length)return "Bang John, belum ada pesan grup Telegram yang masuk ke VEXA.";let t=g,n=g.find(x=>q.includes(x.label.toLowerCase()));if(n)t=[n];const b=[];for(const x of t){const items=(telegramMessages.get(x.id)||[]).slice(-5);if(items.length)b.push(`${x.label}\n${items.map(i=>`• ${i.sender}: ${i.text}`).join("\n")}`);}return b.length?`Bang John, pesan Telegram terbaru yang terbaca:\n\n${b.join("\n\n")}`:"Bang John, grupnya sudah dikenali tetapi belum ada isi pesan baru yang tersimpan.";}
async function sendTelegramMessage(text,targetName=null){if(!process.env.TELEGRAM_BOT_TOKEN)return{ok:false,reason:"token_missing"};let target=targetName?findTelegramChatByName(targetName):null;if(targetName&&!target)return{ok:false,reason:"chat_missing"};if(!target&&telegramChatId)target={id:telegramChatId,label:telegramChatLabel||telegramChatId};if(!target)return{ok:false,reason:"chat_missing"};const sent=await telegramApi("sendMessage",{chat_id:target.id,text:String(text).slice(0,4096)});return{ok:true,messageId:sent?.message_id,chatId:target.id,label:target.label,text:sent?.text||text};}
async function planTelegramAction(client,model,message,history=[]){const groups=[...telegramChats.values()].map(c=>c.label);const recent=Array.isArray(history)?history.slice(-10).filter(i=>i&&["user","assistant"].includes(i.role)&&typeof i.content==="string").map(i=>({role:i.role,content:i.content})):[];const r=await client.responses.create({model,instructions:`Kamu parser tindakan Telegram VEXA. Balas HANYA JSON valid tanpa markdown. Chat/grup dikenal: ${JSON.stringify(groups)}. Pahami percakapan sebelumnya. Jika Bang John sebelumnya menyusun atau merevisi sebuah pesan lalu berkata seperti 'ya begitu, kirim ke grup X', maka text HARUS berisi naskah final yang sebelumnya sudah disepakati, BUKAN kalimat perintah 'ya begitu...'. Jika pesan saat ini sudah memuat isi setelah tanda titik dua, kirim isi itu. Jangan menambah atau mengubah naskah final tanpa diminta. Jika bukan perintah kirim, balas {"action":"none"}. Untuk kirim: {"action":"send","target":"nama grup/chat tujuan","text":"NASKAH FINAL YANG AKAN DITERIMA"}. Target harus salah satu chat/grup dikenal bila tujuan disebut.`,input:[...recent,{role:"user",content:message}]});try{return JSON.parse(cleanJson(r.output_text));}catch{return{action:"none"};}}
async function handleTelegramCommand(client,model,message,history=[]){const plan=await planTelegramAction(client,model,message,history);if(plan.action!=="send")return null;if(!plan.text)return{handled:true,reply:"Bang John, isi pesan Telegramnya belum disebutkan."};const result=await sendTelegramMessage(plan.text,plan.target||null);if(!result.ok&&result.reason==="chat_missing")return{handled:true,reply:"Bang John, grup tujuan belum dikenali VEXA. Saya tidak akan mengirim ke chat lain agar tidak salah tujuan."};if(!result.ok)return{handled:true,reply:"Bang John, pesan Telegram belum berhasil dikirim."};return{handled:true,reply:`Sudah terkirim ke ${result.label}, Bang John.\n\nIsi yang dikirim:\n${result.text}`};}
function selectTelegramMessagesForQuestion(qn){const q=String(qn||"").toLowerCase();let s=[];for(const[id,items]of telegramMessages.entries()){const c=telegramChats.get(id);if(!c)continue;if(q.includes(c.label.toLowerCase())||q.includes("semua grup")||q.includes("kedua grup")||q.includes("telegram"))s.push({chat:c,items:items.slice(-120)});}if(!s.length)s=[...telegramMessages.entries()].map(([id,items])=>({chat:telegramChats.get(id),items:items.slice(-80)})).filter(x=>x.chat);return s;}
async function analyzeTelegramGroups(client,model,question){const s=selectTelegramMessagesForQuestion(question);if(!s.length)return{handled:true,reply:"Bang John, VEXA belum punya pesan grup untuk dianalisis."};const transcript=s.map(({chat,items})=>`GRUP: ${chat.label}\n${items.map(i=>`[${new Date((i.date||0)*1000).toISOString()}] ${i.sender}: ${i.text}`).join("\n")}`).join("\n\n").slice(-30000);const r=await client.responses.create({model,instructions:`Kamu adalah VEXA Executive Monitor milik Bang John. Gunakan HANYA chat yang diberikan. Jawab operasional dengan bagian: RINGKASAN EKSEKUTIF, PRIORITAS BANG JOHN, TUGAS & PIC, KENDALA / RISIKO, KEPUTUSAN / KESEPAKATAN, TINDAK LANJUT YANG DISARANKAN. Jangan mengarang; bila tidak ada tulis 'Belum terlihat dari chat'.`,input:[{role:"user",content:`Pertanyaan Bang John: ${question}\n\n${transcript}`}]});return{handled:true,reply:r.output_text?.trim()||"Bang John, saya belum bisa menyimpulkan percakapan grup tadi."};}
function isTelegramGroupListIntent(m){return /(grup apa|grup mana|daftar grup|grup telegram|yang terbaca|sudah terbaca|terdeteksi|cek koneksi|cek telegram|berapa grup|grup yang ada)/i.test(m);}function isTelegramRecentIntent(m){return /(pesan terbaru|chat terbaru|pesan terakhir|chat terakhir|isi terbaru|apa pesan terakhir|apa isinya|isinya apa|baca pesan|lihat pesan)/i.test(m)&&/(telegram|grup|raya|yunas|project|marketing|keuangan|ksg)/i.test(m);}function isTelegramAnalysisIntent(m){return /(rangkum|ringkas|analisa|analisis|monitor|pantau|prioritas|tugas|pekerjaan|pic|apa yang terjadi|apa yang harus saya lakukan|apa yang perlu saya lakukan|yang belum selesai|belum selesai|tindak lanjut|follow.?up|kesimpulan|masalah|kendala|risiko|keputusan)/i.test(m)&&/(telegram|grup|raya|yunas|project|marketing|keuangan|ksg)/i.test(m);}function isTelegramSendIntent(m){return /(telegram|kirim\s+(?:pesan|chat)|kirim\s+(?:ke|di)\s+(?:grup|telegram)|kirim.*\bgrup\b|langsung\s+kirim|sampaikan.*\bgrup\b|beritahu.*\bgrup\b)/i.test(String(m||""));}
function buildTelegramContextMessage(m,h=[]){const r=Array.isArray(h)?h.slice(-8).filter(i=>i&&typeof i.content==="string").map(i=>i.content).join("\n"):"";return`${r}\n${m}`.trim();}function hasTelegramConversationContext(m,h=[]){const c=buildTelegramContextMessage(m,h).toLowerCase();if(/telegram|grup telegram|pesan telegram|chat telegram/.test(c))return true;return[...telegramChats.values()].some(x=>c.includes(String(x.label||"").toLowerCase()));}function isTelegramFollowUp(m){return/^(periksa|cek|cek lagi|coba lagi|sekarang|bagaimana sekarang|gimana sekarang|yang mana|mana saja|berapa|apa isinya|isinya apa|pesannya apa|apa pesannya|baca|lihat|rangkum|analisa|analisis|monitor|pantau|prioritas|tugas|pekerjaan|tindak lanjut|apa yang harus saya lakukan|apa yang perlu saya lakukan)$/i.test(String(m||"").trim());}
async function planCalendarAction(client,model,message){const now=new Date().toISOString();const r=await client.responses.create({model,instructions:`Kamu parser Google Calendar VEXA. Zona ${timezone}. Waktu ${now}. JSON saja. action none/list/create.`,input:[{role:"user",content:message}]});try{return JSON.parse(cleanJson(r.output_text));}catch{return{action:"none"};}}async function handleCalendarCommand(client,model,message){const p=await planCalendarAction(client,model,message);if(p.action==="none")return null;const auth=getAuthorizedGoogleClient();if(!auth)return{handled:true,reply:"Bang John, Google Calendar belum terhubung ke VEXA."};const cal=google.calendar({version:"v3",auth});if(p.action==="list"){const r=await cal.events.list({calendarId:"primary",timeMin:p.timeMin,timeMax:p.timeMax,singleEvents:true,orderBy:"startTime",maxResults:20});const e=r.data.items||[];return{handled:true,reply:e.length?`Bang John, jadwal ${p.label||"yang diminta"}:\n${e.map((x,i)=>`${i+1}. ${x.summary||"Tanpa judul"} — ${x.start?.dateTime||x.start?.date||""}`).join("\n")}`:`Bang John, tidak ada jadwal di ${p.label||"rentang waktu itu"}.`};}if(p.action==="create"){if(!p.title||!p.start||!p.end)return{handled:true,reply:"Bang John, detail jadwalnya belum cukup."};const c=await cal.events.insert({calendarId:"primary",requestBody:{summary:p.title,start:{dateTime:p.start,timeZone:timezone},end:{dateTime:p.end,timeZone:timezone},description:p.description||"Dibuat oleh VEXA"}});return{handled:true,reply:`Sudah, Bang John. Saya masukkan “${c.data.summary||p.title}” ke Google Calendar.`};}return null;}
app.get("/",(_q,res)=>res.json({service:"VEXA AI Companion",status:"online",version:"3.7.2",voice:"shimmer",calendar:Boolean(googleTokens),telegram:Boolean(process.env.TELEGRAM_BOT_TOKEN),telegramGroups:getTelegramGroupRows().length,persistence:{file:stateFile,volumeRecommended:activeStateDir==="/data"}}));app.get("/health",(_q,res)=>res.json({ok:true,service:"VEXA",version:"3.7.2",voice:"shimmer",calendar:Boolean(googleTokens),telegram:Boolean(process.env.TELEGRAM_BOT_TOKEN),telegramGroups:getTelegramGroupRows().length,persistence:{active:true,stateDir:activeStateDir}}));
app.get("/auth/google",(_q,res)=>{try{const c=makeOAuthClient();res.redirect(c.generateAuthUrl({access_type:"offline",prompt:"consent",scope:["https://www.googleapis.com/auth/calendar.events"]}));}catch(e){res.status(500).send("Google OAuth belum siap di server VEXA.");}});app.get("/auth/google/callback",async(req,res)=>{try{const code=req.query.code;if(!code)return res.status(400).send("Kode Google tidak ditemukan.");const c=makeOAuthClient(),{tokens}=await c.getToken(code);googleTokens={...googleTokens,...tokens};saveStateNow();res.send("Google Calendar terhubung. Silakan kembali ke VEXA.");}catch(e){console.error("Google auth callback error:",e);res.status(500).send("VEXA gagal menyelesaikan koneksi Google Calendar.");}});app.get("/api/calendar/status",(_q,res)=>res.json({ok:true,connected:Boolean(googleTokens),persistent:fs.existsSync(stateFile)}));
app.get("/api/telegram/status",async(_q,res)=>{let info=null;try{if(process.env.TELEGRAM_BOT_TOKEN)try{info=await telegramApi("getWebhookInfo",{});}catch{}res.json({ok:true,configured:Boolean(process.env.TELEGRAM_BOT_TOKEN),webhook:telegramWebhookUrl,webhookInfo:info,groups:getTelegramGroupRows(),persistent:fs.existsSync(stateFile)});}catch{res.status(500).json({ok:false});}});app.get("/api/telegram/groups",(_q,res)=>res.json({ok:true,groups:getTelegramGroupRows()}));app.get("/api/telegram/recent",(_q,res)=>res.json({ok:true,reply:getRecentTelegramReply("telegram")}));app.post("/api/telegram/webhook",(req,res)=>{try{const m=req.body?.message||req.body?.edited_message||req.body?.channel_post||req.body?.edited_channel_post;if(m)rememberTelegramMessage(m);res.sendStatus(200);}catch{res.sendStatus(200);}});
app.post("/api/chat",async(req,res)=>{try{const{message,history=[]}=req.body||{};if(!message||typeof message!=="string")return res.status(400).json({error:"Pesan wajib diisi."});const apiKey=process.env.OPENAI_API_KEY,model=process.env.OPENAI_MODEL;if(!apiKey||!model)return res.status(500).json({error:"Konfigurasi AI belum lengkap."});const client=new OpenAI({apiKey});const ctx=buildTelegramContextMessage(message,history),explicit=hasTelegramConversationContext(message,history)||/telegram|grup|marketing yunas|raya|project|keuangan|ksg/i.test(message);if(explicit)setChatTopic("telegram");const active=explicit||getChatTopic()==="telegram";
if(isTelegramGroupListIntent(message)||(active&&isTelegramFollowUp(message)&&/(periksa|cek|berapa|yang mana|mana saja)/i.test(message)))return res.json({ok:true,reply:formatTelegramGroupsReply(),model,tool:"telegram_groups"});if(isTelegramRecentIntent(message)||(active&&isTelegramFollowUp(message)&&/(apa isinya|baca|lihat)/i.test(message)))return res.json({ok:true,reply:getRecentTelegramReply(ctx),model,tool:"telegram_recent"});if(isTelegramAnalysisIntent(message)||(active&&isTelegramFollowUp(message)&&/(rangkum|analisa|monitor|prioritas|tugas|tindak lanjut)/i.test(message))){try{const r=await analyzeTelegramGroups(client,model,ctx);return res.json({ok:true,reply:r.reply,model,tool:"telegram_executive_monitor"});}catch(e){console.error(e);return res.json({ok:true,reply:"Bang John, analisis Telegram belum berhasil.",model,tool:"telegram_executive_monitor"});}}
if(isTelegramSendIntent(message)){try{setChatTopic("telegram");const tg=await handleTelegramCommand(client,model,message,history);if(tg?.handled)return res.json({ok:true,reply:tg.reply,model,tool:"telegram"});}catch(e){console.error("VEXA Telegram command error:",e);return res.json({ok:true,reply:"Bang John, pesan Telegram belum berhasil dikirim.",model,tool:"telegram"});}}
if(/kalender|calendar|jadwal|meeting|rapat|agenda/i.test(message)){try{const cal=await handleCalendarCommand(client,model,message);if(cal?.handled)return res.json({ok:true,reply:cal.reply,model,tool:"google_calendar"});}catch(e){return res.json({ok:true,reply:"Bang John, perintah Calendar belum berhasil diproses.",model,tool:"google_calendar"});}}
const safe=Array.isArray(history)?history.slice(-12).filter(i=>i&&["user","assistant"].includes(i.role)&&typeof i.content==="string"):[];const r=await client.responses.create({model,instructions:"Kamu VEXA, personal AI companion Bang John. Bahasa Indonesia natural, ringkas, tajam. Jangan mengarang tindakan. VEXA dapat membaca, menganalisis, dan mengirim Telegram melalui jalur sistem.",input:[...safe.map(i=>({role:i.role,content:i.content})),{role:"user",content:message}]});res.json({ok:true,reply:r.output_text?.trim()||"Maaf Bang John, belum ada jawaban.",model});}catch(e){console.error(e);res.status(500).json({ok:false,error:"VEXA sedang mengalami gangguan."});}});
app.post("/api/speech",async(req,res)=>{try{const{text}=req.body||{};if(!text)return res.status(400).json({error:"Teks wajib diisi."});const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});const speech=await client.audio.speech.create({model:"gpt-4o-mini-tts",voice:"shimmer",input:String(text).slice(0,4096),instructions:"Speak in natural conversational Indonesian as a warm young female personal AI companion.",response_format:"mp3",speed:1});res.type("audio/mpeg").send(Buffer.from(await speech.arrayBuffer()));}catch(e){res.status(500).json({ok:false,error:"VEXA belum dapat menghasilkan suara."});}});app.use((e,_q,res,_n)=>res.status(500).json({ok:false,error:"Terjadi kesalahan pada server VEXA."}));function shutdown(){saveStateNow();process.exit(0);}process.on("SIGTERM",shutdown);process.on("SIGINT",shutdown);app.listen(port,()=>{console.log(`VEXA backend aktif di port ${port}`);console.log(`VEXA persistence: ${stateFile}`);if(process.env.TELEGRAM_BOT_TOKEN)telegramApi("setWebhook",{url:telegramWebhookUrl,allowed_updates:["message","edited_message","channel_post","edited_channel_post"],drop_pending_updates:false}).then(()=>console.log("Telegram webhook aktif:",telegramWebhookUrl)).catch(e=>console.error(e.message));});